
# create cohorts
cohort_2107_be = Cohort.create(name: "2107 BE", start_date: Date.parse('01-07-2021'), graduation_date: Date.parse('01-02-2022') )
cohort_2103_fe = Cohort.create(name: "2103 FE", start_date: Date.parse('01-03-2021'), graduation_date: Date.parse('01-10-2021') )
cohort_2105_be = Cohort.create(name: "2105 BE", start_date: Date.parse('01-05-2021'), graduation_date: Date.parse('01-12-2021') )
cohort_2009_fe = Cohort.create(name: "2009 FE", start_date: Date.parse('01-09-2020'), graduation_date: Date.parse('01-04-2021') )

# create students for specific cohorts
cohort_2107_be.students.create(first_name: "Jessie", last_name: "Smith", preferred_name: "Jess", pronouns: "xe/xem",  email: "Jessie@email.com", github_username: "Jessie_github", slack_username: "Jessie_slack")
cohort_2107_be.students.create(first_name: "Marion", last_name: "Johnson", preferred_name: "Marion", pronouns: "she/they",  email: "Marion@email.com", github_username: "Marion_github", slack_username: "Marion_slack")
cohort_2107_be.students.create(first_name: "Alva", last_name: "Brown",  preferred_name: "Alva", pronouns: "ze/zir",  email: "Alva@email.com", github_username: "Alva_github", slack_username: "Alva_slack")
cohort_2107_be.students.create(first_name: "Ollie", last_name: "Jones",  preferred_name: "Ollie", pronouns: "he/they",  email: "Ollie@email.com", github_username: "Ollie_github", slack_username: "Ollie_slack")
cohort_2107_be.students.create(first_name: "Jodie", last_name: "Garcia",  preferred_name: "Jodie", pronouns: "she/her",  email: "Jodie@email.com", github_username: "Jodie_github", slack_username: "Jodie_slack")
cohort_2107_be.students.create(first_name: "Cleo", last_name: "Miller", preferred_name: "Cleo", pronouns: "they/them",  email: "Cleo@email.com", github_username: "Cleo_github", slack_username: "Cleo_slack")
cohort_2107_be.students.create(first_name: "Kai", last_name: "Rodriguez", preferred_name: "Kai", pronouns: "xe/xem",  email: "Kai@email.com", github_username: "Kai_github", slack_username: "Kai_slack")
cohort_2107_be.students.create(first_name: "Luca", last_name: "Martinez", preferred_name: "Marty", pronouns: "she/they",  email: "Luca@email.com", github_username: "Luca_github", slack_username: "Luca_slack")
cohort_2107_be.students.create(first_name: "Hunter", last_name: "Hernandez", preferred_name: "Hunter", pronouns: "he/him",  email: "Hunter@email.com", github_username: "Hunter_github", slack_username: "Hunter_slack")
cohort_2107_be.students.create(first_name: "Quinn", last_name: "Lopez", preferred_name: "Quinn", pronouns: "ze/zir",  email: "Quinn@email.com", github_username: "Quinn_github", slack_username: "Quinn_slack")
cohort_2107_be.students.create(first_name: "Atlas", last_name: "Gonzales", preferred_name: "Atlas", pronouns: "he/they",  email: "Atlas@email.com", github_username: "Atlas_github", slack_username: "Atlas_slack")
cohort_2107_be.students.create(first_name: "Elliot", last_name: "Wilson", preferred_name: "Elle", pronouns: "she/her",  email: "Elliot@email.com", github_username: "Elliot_github", slack_username: "Elliot_slack")
cohort_2107_be.students.create(first_name: "Parker", last_name: "Anderson", preferred_name: "Parker", pronouns: "they/them",  email: "Parker@email.com", github_username: "Parker_github", slack_username: "Parker_slack")
cohort_2107_be.students.create(first_name: "Avery", last_name: "Thomas", preferred_name: "Avery", pronouns: "ze/hir",  email: "Avery@email.com", github_username: "Avery_github", slack_username: "Avery_slack")
cohort_2107_be.students.create(first_name: "River", last_name: "Taylor", preferred_name: "River", pronouns: "xe/xem",  email: "River@email.com", github_username: "River_github", slack_username: "River_slack")
cohort_2107_be.students.create(first_name: "Hayden", last_name: "Jackson", preferred_name: "Hayden", pronouns: "he/him",  email: "Hayden@email.com", github_username: "Hayden_github", slack_username: "Hayden_slack")
cohort_2107_be.students.create(first_name: "Remi", last_name: "Martin", preferred_name: "Remi", pronouns: "ze/zir",  email: "Remi@email.com", github_username: "Remi_github", slack_username: "Remi_slack")
cohort_2103_fe.students.create(first_name: "Logan", last_name: "Lee", preferred_name: "Logan", pronouns: "he/they",  email: "Logan@email.com", github_username: "Logan_github", slack_username: "Logan_slack")
cohort_2103_fe.students.create(first_name: "Riley", last_name: "Perez", preferred_name: "Perez", pronouns: "she/her",  email: "Riley@email.com", github_username: "Riley_github", slack_username: "Riley_slack")
cohort_2103_fe.students.create(first_name: "Reese", last_name: "Thompson", preferred_name: "Reese", pronouns: "they/them",  email: "Reese@email.com", github_username: "Reese_github", slack_username: "Reese_slack")
cohort_2103_fe.students.create(first_name: "Jude", last_name: "White", preferred_name: "Jude", pronouns: "ze/hir",  email: "Jude@email.com", github_username: "Jude_github", slack_username: "Jude_slack")
cohort_2103_fe.students.create(first_name: "Ava", last_name: "Harris", preferred_name: "Ava", pronouns: "xe/xem",  email: "Ava@email.com", github_username: "Ava_github", slack_username: "Ava_slack")
cohort_2103_fe.students.create(first_name: "Jalen", last_name: "Sanchez", preferred_name: "Jude", pronouns: "she/they",  email: "Jalen@email.com", github_username: "Jalen_github", slack_username: "Jalen_slack")
cohort_2103_fe.students.create(first_name: "Asa", last_name: "Clark", preferred_name: "Asa", pronouns: "he/him",  email: "Asa@email.com", github_username: "Asa_github", slack_username: "Asa_slack")
cohort_2103_fe.students.create(first_name: "Rowan", last_name: "Ramirez", preferred_name: "Rowan", pronouns: "ze/zir",  email: "Rowan@email.com", github_username: "Rowan_github", slack_username: "Rowan_slack")
cohort_2103_fe.students.create(first_name: "Guadalupe", last_name: "Robinson", preferred_name: "Guadalupe", pronouns: "she/her",  email: "Guadalupe@email.com", github_username: "Guadalupe_github", slack_username: "Guadalupe_slack")
cohort_2103_fe.students.create(first_name: "Carey", last_name: "Walker", preferred_name: "Walker", pronouns: "they/them",  email: "Carey@email.com", github_username: "Carey_github", slack_username: "Carey_slack")
cohort_2103_fe.students.create(first_name: "Tommie", last_name: "Young", preferred_name: "Tommie", pronouns: "ze/hir",  email: "Tommie@email.com", github_username: "Tommie_github", slack_username: "Tommie_slack")
cohort_2103_fe.students.create(first_name: "Angel", last_name: "Allen", preferred_name: "Angel", pronouns: "xe/xem",  email: "Angel@email.com", github_username: "Angel_github", slack_username: "Angel_slack")
cohort_2103_fe.students.create(first_name: "Hollis", last_name: "King", preferred_name: "Holly", pronouns: "she/they",  email: "Hollis@email.com", github_username: "Hollis_github", slack_username: "Hollis_slack")
cohort_2103_fe.students.create(first_name: "Sammie", last_name: "Wright", preferred_name: "Sam", pronouns: "he/him",  email: "Sammie@email.com", github_username: "Sammie_github", slack_username: "Sammie_slack")
cohort_2103_fe.students.create(first_name: "Jamie", last_name: "Scott", preferred_name: "Jamie", pronouns: "ze/zir",  email: "Jamie@email.com", github_username: "Jamie_github", slack_username: "Jamie_slack")
cohort_2103_fe.students.create(first_name: "Kris", last_name: "Torres", preferred_name: "Kris", pronouns: "he/they",  email: "Kris@email.com", github_username: "Kris_github", slack_username: "Kris_slack")
cohort_2103_fe.students.create(first_name: "Tracy", last_name: "Hill", preferred_name: "Tracy", pronouns: "they/them",  email: "Tracy@email.com", github_username: "Tracy_github", slack_username: "Tracy_slack")
cohort_2103_fe.students.create(first_name: "Merrill", last_name: "Flores", preferred_name: "Merrill", pronouns: "ze/hir",  email: "Merrill@email.com", github_username: "Merrill_github", slack_username: "Merrill_slack")
cohort_2103_fe.students.create(first_name: "Noel", last_name: "Green", preferred_name: "Noel", pronouns: "xe/xem",  email: "Noel@email.com", github_username: "Noel_github", slack_username: "Noel_slack")
cohort_2103_fe.students.create(first_name: "Johnnie", last_name: "Nelson", preferred_name: "Johnnie", pronouns: "he/him",  email: "Johnnie@email.com", github_username: "Johnnie_github", slack_username: "Johnnie_slack")
cohort_2103_fe.students.create(first_name: "Ariel", last_name: "Baker", preferred_name: "Arie", pronouns: "ze/zir",  email: "Ariel@email.com", github_username: "Ariel_github", slack_username: "Ariel_slack")
cohort_2103_fe.students.create(first_name: "Jan", last_name: "Hall", preferred_name: "JanHa", pronouns: "he/they",  email: "Jan@email.com", github_username: "Jan_github", slack_username: "Jan_slack")
cohort_2103_fe.students.create(first_name: "Casey", last_name: "Rivera", preferred_name: "Casey", pronouns: "she/her",  email: "Casey@email.com", github_username: "Casey_github", slack_username: "Casey_slack")
cohort_2103_fe.students.create(first_name: "Jackie", last_name: "Campbell", preferred_name: "Jackie", pronouns: "they/them",  email: "Jackie@email.com", github_username: "Jackie_github", slack_username: "Jackie_slack")
cohort_2103_fe.students.create(first_name: "Kerry", last_name: "Mitchell", preferred_name: "Kerry", pronouns: "ze/hir",  email: "Kerry@email.com", github_username: "Kerry_github", slack_username: "Kerry_slack")
cohort_2103_fe.students.create(first_name: "Finley", last_name: "Roberts", preferred_name: "Fin", pronouns: "she/they",  email: "Finley@email.com", github_username: "Finley_github", slack_username: "Finley_slack")
cohort_2105_be.students.create(first_name: "Skylar", last_name: "Gomez", preferred_name: "Skylar", pronouns: "he/him",  email: "Skylar@email.com", github_username: "Skylar_github", slack_username: "Skylar_slack")
cohort_2105_be.students.create(first_name: "Justice", last_name: "Phillips", preferred_name: "Justice", pronouns: "ze/zir",  email: "Justice@email.com", github_username: "Justice_github", slack_username: "Justice_slack")
cohort_2105_be.students.create(first_name: "Rene", last_name: "Evans", preferred_name: "Rene", pronouns: "he/they",  email: "Rene@email.com", github_username: "Rene_github", slack_username: "Rene_slack")
cohort_2105_be.students.create(first_name: "Darian", last_name: "Turner", preferred_name: "Darian", pronouns: "she/her",  email: "Darian@email.com", github_username: "Darian_github", slack_username: "Darian_slack")
cohort_2105_be.students.create(first_name: "Frankie", last_name: "Diaz", preferred_name: "Frankie", pronouns: "they/them",  email: "Frankie@email.com", github_username: "Frankie_github", slack_username: "Frankie_slack")
cohort_2105_be.students.create(first_name: "Oakley", last_name: "Parker", preferred_name: "Oakley", pronouns: "ze/hir",  email: "Oakley@email.com", github_username: "Oakley_github", slack_username: "Oakley_slack")
cohort_2105_be.students.create(first_name: "Robbie", last_name: "Cruz", preferred_name: "Robbie", pronouns: "xe/xem",  email: "Robbie@email.com", github_username: "Robbie_github", slack_username: "Robbie_slack")
cohort_2105_be.students.create(first_name: "Remy", last_name: "Edwards", preferred_name: "Remy", pronouns: "she/they",  email: "Remy@email.com", github_username: "Remy_github", slack_username: "Remy_slack")
cohort_2105_be.students.create(first_name: "Milan", last_name: "Collins", preferred_name: "Milan", pronouns: "he/him",  email: "Milan@email.com", github_username: "Milan_github", slack_username: "Milan_slack")
cohort_2105_be.students.create(first_name: "Jaylin", last_name: "Reyes", preferred_name: "Jaylin", pronouns: "ze/zir",  email: "Jaylin@email.com", github_username: "Jaylin_github", slack_username: "Jaylin_slack")
cohort_2105_be.students.create(first_name: "Devan", last_name: "Stewart", preferred_name: "Devan", pronouns: "he/they",  email: "Devan@email.com", github_username: "Devan_github", slack_username: "Devan_slack")
cohort_2105_be.students.create(first_name: "Armani", last_name: "Morris", preferred_name: "Armani", pronouns: "she/her",  email: "Armani@email.com", github_username: "Armani_github", slack_username: "Armani_slack")
cohort_2105_be.students.create(first_name: "Stevie", last_name: "Murphy", preferred_name: "Stevie", pronouns: "ze/hir",  email: "Stevie@email.com", github_username: "Stevie_github", slack_username: "Stevie_slack")
cohort_2105_be.students.create(first_name: "Channing", last_name: "Cook", preferred_name: "Channing", pronouns: "xe/xem",  email: "Channing@email.com", github_username: "Channing_github", slack_username: "Channing_slack")
cohort_2105_be.students.create(first_name: "Gerry", last_name: "Rogers", preferred_name: "Roger", pronouns: "she/they",  email: "Gerry@email.com", github_username: "Gerry_github", slack_username: "Gerry_slack")
cohort_2105_be.students.create(first_name: "Monroe", last_name: "Gutierrez", preferred_name: "Monroe", pronouns: "he/him",  email: "Monroe@email.com", github_username: "Monroe_github", slack_username: "Monroe_slack")
cohort_2105_be.students.create(first_name: "Kirby", last_name: "Ortiz", preferred_name: "Kirby", pronouns: "ze/zir",  email: "Kirby@email.com", github_username: "Kirby_github", slack_username: "Kirby_slack")
cohort_2105_be.students.create(first_name: "Azariah", last_name: "Morgan", preferred_name: "Azariah", pronouns: "he/they",  email: "Azariah@email.com", github_username: "Azariah_github", slack_username: "Azariah_slack")
cohort_2009_fe.students.create(first_name: "Santana", last_name: "Cooper", preferred_name: "Santana", pronouns: "she/her",  email: "Santana@email.com", github_username: "Santana_github", slack_username: "Santana_slack")
cohort_2009_fe.students.create(first_name: "Briar", last_name: "Bailey", preferred_name: "Briar", pronouns: "ze/hir",  email: "Briar@email.com", github_username: "Briar_github", slack_username: "Briar_slack")
cohort_2009_fe.students.create(first_name: "Brooklyn", last_name: "Reed", preferred_name: "Lyn", pronouns: "xe/xem",  email: "Brooklyn@email.com", github_username: "Brooklyn_github", slack_username: "Brooklyn_slack")
cohort_2009_fe.students.create(first_name: "Campbell", last_name: "Kelly", preferred_name: "Campbell", pronouns: "she/they",  email: "Campbell@email.com", github_username: "Campbell_github", slack_username: "Campbell_slack")
cohort_2009_fe.students.create(first_name: "Dallas", last_name: "Howard", preferred_name: "Kevin", pronouns: "he/him",  email: "Dallas@email.com", github_username: "Dallas_github", slack_username: "Dallas_slack")
cohort_2009_fe.students.create(first_name: "Gray", last_name: "Ramos", preferred_name: "Gray", pronouns: "ze/zir",  email: "Gray@email.com", github_username: "Gray_github", slack_username: "Gray_slack")
cohort_2009_fe.students.create(first_name: "Bellamy", last_name: "Kim", preferred_name: "Bellamy", pronouns: "he/they",  email: "Bellamy@email.com", github_username: "Bellamy_github", slack_username: "Bellamy_slack")
cohort_2009_fe.students.create(first_name: "Charlie", last_name: "Cox", preferred_name: "Chuck", pronouns: "she/her",  email: "Charlie@email.com", github_username: "Charlie_github", slack_username: "Charlie_slack")
cohort_2009_fe.students.create(first_name: "Dakota", last_name: "Ward", preferred_name: "Dakota", pronouns: "they/them",  email: "Dakota@email.com", github_username: "Dakota_github", slack_username: "Dakota_slack")
cohort_2009_fe.students.create(first_name: "Denver", last_name: "Richardson", preferred_name: "Austin", pronouns: "ze/hir",  email: "Denver@email.com", github_username: "Denver_github", slack_username: "Denver_slack")
cohort_2009_fe.students.create(first_name: "Emerson", last_name: "Watson", preferred_name: "Emerson", pronouns: "xe/xem",  email: "Emerson@email.com", github_username: "Emerson_github", slack_username: "Emerson_slack")
cohort_2009_fe.students.create(first_name: "Tatum", last_name: "Bennet", preferred_name: "Tatum", pronouns: "she/her",  email: "Tatum@email.com", github_username: "Tatum_github", slack_username: "Tatum_slack")
cohort_2009_fe.students.create(first_name: "Greer", last_name: "Gray", preferred_name: "Greer", pronouns: "they/them",  email: "Greer@email.com", github_username: "Greer_github", slack_username: "Greer_slack")
cohort_2009_fe.students.create(first_name: "Haven", last_name: "Mendoza", preferred_name: "Haven", pronouns: "ze/hir",  email: "Haven@email.com", github_username: "Haven_github", slack_username: "Haven_slack")
cohort_2009_fe.students.create(first_name: "Indigo", last_name: "Ruiz", preferred_name: "Dig", pronouns: "xe/xem",  email: "Indigo@email.com", github_username: "Indigo_github", slack_username: "Indigo_slack")
cohort_2009_fe.students.create(first_name: "Jordan", last_name: "Hughes", preferred_name: "Jordan", pronouns: "she/they",  email: "Jordan@email.com", github_username: "Jordan_github", slack_username: "Jordan_slack")
cohort_2009_fe.students.create(first_name: "Lennox", last_name: "Price", preferred_name: "Lennox", pronouns: "he/him",  email: "Lennox@email.com", github_username: "Lennox_github", slack_username: "Lennox_slack")
